language: objective-c
before_install:
    - brew update
    - brew install xctool
    - brew install cocoapods
    - pod install
script:
    - xctool -workspace Example/ExampleSSDataSources.xcworkspace -scheme ExampleSSDataSources -sdk iphonesimulator build test ONLY_ACTIVE_ARCH=NO
